builds:
- main: .
  binary: catalog-cd
  env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  goos:
  - windows
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  - s390x
  - "386"
  - mips64le
  - ppc64le
archives:
- name_template: >-
    {{- .Binary }}_
    {{- .Version }}_
    {{- .Os }}_
    {{- if eq .Arch "amd64" }}x86_64
    {{- else if eq .Arch "386" }}i386
    {{- else if eq .Arch "darwin" }}MacOS
    {{- else if eq .Arch "linux" }}Linux
    {{- else if eq .Arch "windows" }}Windows
    {{- else }}{{ .Arch }}{{ end }}
    {{- if .Arm }}v{{ .Arm }}{{ end -}}
    {{- if .Mips }}_{{ .Mips }}{{ end -}}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - '^docs:'
    - '^test:'
