# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types: ["pre-push"]
exclude: '(^docs/themes/hugo-book|^vendor|.*golden$|^\.vale)'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-shebang-scripts-are-executable
      - id: check-json
      - id: check-vcs-permalinks
      - id: detect-private-key
        exclude: ".*_test.go"
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
  - repo: local
    hooks:
      - id: test
        name: "Unit testing"
        entry: make
        args: ["test"]
        language: system
        types: [go]
        pass_filenames: false
      - id: lint
        name: "Linting"
        entry: make
        args: ["lint"]
        language: system
        pass_filenames: false
