---
name: Generate `pull-from` matrix output
description: |
  Generates a GitHub Worklow outputs that can then be consumed with `strategy.matrix` from an `externals.yaml` file.
inputs:
  version:
    description: 'Version of catalog-cd to install (tip, latest-release, v0.1.0, etc.)'
    require: false
    default: 'latest-release'
  name:
    description: 'Name of the repository we pull'
    required: true
  url:
    description: 'URL of the repository we pull'
    required: true
  type:
    description: 'Type of resources we pull'
    required: true
    default: 'task'
  ignoreVersions:
    description: 'Versions to ignore'
    required: 'true'
    default: ''
  target:
    description: 'The path where catalog-cd will write the resources pulled'
    required: true
    default: .
outputs:
  pull-from-list:
    description: |
      `strategy.matrix` compatible output containing the "matrix" of pull-from to run.
runs:
  using: composite
  steps:
    - uses: openshift-pipelines/catalog-cd/actions/setup-catalog-cd
      with:
        version: ${{ inputs.version }}
    - id: set-matrix
      name: Generate catalog matrix
      run: |
        set -Eeu
        catalog-cd catalog generate-from \
                 --name ${{ inputs.name }} \
                 --url ${{ inputs.url }} \
                 --type ${{ inputs.type }} \
                 --ignore-versions "${{ inputs.ignoreVersions }}" \
                 ${{ inputs.target }}
